### ISSUE TITLE
TypeError: 'type' object is not subscriptable in class Enum

### ISSUE THREAD

**Issue by jackeichen** [python-scsi/python-scsi#125]
Python version 3.7.9, error occured like this

   def keys(cls) -> list[str]:
TypeError: 'type' object is not subscriptable

I think the feature is not ready in 3.7.9, but the setup.cfg is ~=3.7.

**Comment by rosjat** [comment]
well the question is what you wanna do? this is simply a type annotation you post  but without a traceback its hard to say whats going on.

**Comment by jackeichen** [comment]
Here is the traceback：
```
>>> import pyscsi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\Desktop\tools\python-scsi\pyscsi\__init__.py", line 5, in <module>
    from .pyscsi import *
  File "C:\Users\Administrator\Desktop\tools\python-scsi\pyscsi\pyscsi\scsi.py", line 9, in <module>
    from pyscsi.pyscsi.scsi_cdb_atapassthrough12 import ATAPassThrough12
  File "C:\Users\Administrator\Desktop\tools\python-scsi\pyscsi\pyscsi\scsi_cdb_atapassthrough12.py", line 8, in <module>
    from pyscsi.pyscsi.scsi_command import SCSICommand
  File "C:\Users\Administrator\Desktop\tools\python-scsi\pyscsi\pyscsi\scsi_command.py", line 9, in <module>
    from pyscsi.pyscsi.scsi_exception import SCSIDeviceCommandExceptionMeta as ExMETA
  File "C:\Users\Administrator\Desktop\tools\python-scsi\pyscsi\pyscsi\scsi_exception.py", line 9, in <module>
    from pyscsi.pyscsi.scsi_sense import SCSICheckCondition
  File "C:\Users\Administrator\Desktop\tools\python-scsi\pyscsi\pyscsi\scsi_sense.py", line 9, in <module>
    from pyscsi.utils.converter import decode_bits
  File "C:\Users\Administrator\Desktop\tools\python-scsi\pyscsi\utils\__init__.py", line 8, in <module>
    from .enum import *
  File "C:\Users\Administrator\Desktop\tools\python-scsi\pyscsi\utils\enum.py", line 18, in <module>
    class Enum(type):
  File "C:\Users\Administrator\Desktop\tools\python-scsi\pyscsi\utils\enum.py", line 82, in Enum
    def keys(cls) -> list[str]:
TypeError: 'type' object is not subscriptable
```

**Comment by rosjat** [comment]
does this happens on import or when you try to use the the key or add methods of the Enum class ?

I will look into it, i dont think its the annotation itself but as you stated in 3.7 you might need to use List from typing but then again we dont aim to support 3.7 we aim on 3.9 or higher so I will also go through the setup files to change the version of python required to run the code.

**Comment by jackeichen** [comment]
This happens on import.

Does it mean pyscsi is not going to do forward compatible(in python 3.7.x or older version)?

**Comment by rosjat** [comment]
well since most distros already switched to python 3.9 or greater there is no need to try to make it compatible with a lesser version if we really wanna go forward with the project. if there is a specific need for versions lesser then 3.9 we might consider branching off to support this but the master branch should go forward to support features we get in versions 3.9 and beyond

**Comment by rosjat** [comment]
I confirmed that the annotation with the actual type in 3.7 isnt supportet so the fix here will be 

`from typing import List` 
 
and use it instead or 

`from __future__ import annotations`

but the 2nd  import doesnt really help tools like mypy to evaluate the proper type of the annotated variable. We should keep in mind that using List from typing will not be encuraged after 3.9 and will be removed eventually.  Going forward with typing in the module there should be a good reason for making use of the aliases in typing when it's discuraged. So if this is just because you run a machine with 3.7 as your dev env you might consider updating to a more recent version of python. As mentioned before most distros already moved on to python versions greater then 3.9 anyway.

as for the bug i will add the `List` import later to get it working with python 3.7 and 3.8

**Comment by jackeichen** [comment]
Thanks for the wrok and make it clear. I  will test in python 3.9 and close this issue later.

**Comment by rosjat** [comment]
#126 should fix the problem for python 3.7 and 3.8
