### ISSUE TITLE
pip install issue  in python 3.7.9

### ISSUE THREAD

**Issue by jackeichen** [python-scsi/python-scsi#127]
I cannot install pyscsi through pip. Here is my output:

```
PS C:\Users\Administrator\Desktop\python-scsi-master\python-scsi-master> pip install .
Processing c:\users\administrator\desktop\python-scsi-master\python-scsi-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\config\setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      Traceback (most recent call last):
        File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\dist.py", line 492, in __init__
          for k, v in attrs.items()
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools\dist.py", line 912, in finalize_options
          ep(self)
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools_scm\integration.py", line 127, in infer_version
          _assign_version(dist, config)
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools_scm\integration.py", line 63, in _assign_version
          _version_missing(config)
        File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-51f2sj6l\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 109, in _version_missing
          f"setuptools-scm was unable to detect version for {config.absolute_root}.\n\n"
      LookupError: setuptools-scm was unable to detect version for C:\Users\Administrator\Desktop\python-scsi-master\python-scsi-master.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

And this is my configuration:
```
PS C:\Users\Administrator\Desktop\python-scsi-master\python-scsi-master> python --version
Python 3.7.9
PS C:\Users\Administrator\Desktop\python-scsi-master\python-scsi-master> pip --version
pip 23.0.1 from c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)
PS C:\Users\Administrator\Desktop\python-scsi-master\python-scsi-master> pip list
Package            Version
------------------ -------
importlib-metadata 6.0.0
packaging          23.0
pip                23.0.1
PYDISKCMD          0.2.4
setuptools         47.1.0
setuptools-scm     7.1.0
tomli              2.0.1
typing_extensions  4.5.0
zipp               3.15.0
PS C:\Users\Administrator\Desktop\python-scsi-master\python-scsi-master>
```

**Comment by jackeichen** [comment]
And I can install it after delete the file "pyproject.toml".

**Comment by rosjat** [comment]
well i guess the python 3.7.9 version cant handle one of the requirements in pyproject.toml

first thing to check would be what version 3.7 can install of the build dependencies like setuptools and setuptools_scm
Also you build that on a windows machine so the third_party  list wont work at al since those packages are aimed on linux.

**Comment by jackeichen** [comment]
- well i guess the python 3.7.9 version cant handle one of the requirements in pyproject.toml

first thing to check would be what version 3.7 can install of the build dependencies like setuptools and setuptools_scm

R: I don't know much about setuptools,what test can i do for it, or it is not a issue.


- Also you build that on a windows machine so the third_party list wont work at al since those packages are aimed on linux.

R: Yes, it aims to work for linux. But it can also serve commands structure to windows, with init a proper windows scsi_device(at least scsi read, atapassthrough16 in my test)

**Comment by rosjat** [comment]
it sure can but if you say it installs without the pyproject.toml then something in there seems to cause a problem and since not much is in there you can just try to figure it out by removing things . When you identify the cause you can start working around it. If you wanna make it compatible with a package that supports scsi on windows then you simply add proper checks for it

**Comment by jackeichen** [comment]
I cannot fix this issue by removing something step by step.

And I notice that "LookupError: setuptools-scm was unable to detect version for C:\Users\Administrator\Desktop\python-scsi-master\python-scsi-master." in the process. So I guess the legacy install mode(after deleting pyproject.toml) Do Not detect python-scsi version.

Something wrong in the python-scsi version,  although I don’t know where it is.

**Comment by rosjat** [comment]
> I cannot fix this issue by removing something step by step.

but thats the way you would try to figure it out  

> And I notice that "LookupError: setuptools-scm was unable to detect version for C:\Users\Administrator\Desktop\python-scsi-master\python-scsi-master." in the process. So I guess the legacy install mode(after deleting pyproject.toml) Do Not detect python-scsi version.
> 
pyproject.toml defines how python-scsi can be build with and setuptools-scm you can more or less firgure stuff out from the source control like git. and since we use git tags to set the version  setuptools-scm figures out the version from the tags

> Something wrong in the python-scsi version, although I don’t know where it is.
again  i cant debug your setup for you since i dont really know what you are doing! 

it is not helpful to simply claim something is broken just because it doesnt work in your environment. So maybe try to set up a clean venv and try to install python scsi from pip. If it breaks still post your steps to come to the point.

a simple test on my windows with a python 3.7 virtual env 
```

 virtualenv --python C:\Users\mr\AppData\Local\Programs\Python\Python37\python.exe  env
created virtual environment CPython3.7.9.final.0-64 in 641ms
  creator CPython3Windows(dest=D:\test\venv\env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\mr\AppData\Local\pypa\virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

.\env\Scripts\activate
git clone https://github.com/python-scsi/python-scsi.git
Cloning into 'python-scsi'...
remote: Enumerating objects: 3194, done.
remote: Counting objects: 100% (617/617), done.
remote: Compressing objects: 100% (204/204), done.
remote: Total 3194 (delta 479), reused 492 (delta 413), pack-reused 2577
Receiving objects: 100% (3194/3194), 822.93 KiB | 9.14 MiB/s, done.
Resolving deltas: 100% (2221/2221), done.
cd .\python-scsi\
pip install .
Processing d:\test\venv\python-scsi
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: PYSCSI
  Building wheel for PYSCSI (pyproject.toml) ... done
  Created wheel for PYSCSI: filename=PYSCSI-2.1.1.dev33+gdaef7da-py3-none-any.whl size=105285 sha256=fbedf4f81122b4287fac520e587f0d3bb849a1251571d2a0b8d29ff4c3f6149f
  Stored in directory: c:\users\mr\appdata\local\pip\cache\wheels\9e\26\94\ff072f9fa2f382dd1f44afc4840c19a5dda2ab5abfd732dbfc
Successfully built PYSCSI
Installing collected packages: PYSCSI
Successfully installed PYSCSI-2.1.1.dev33+gdaef7da
```

**Comment by jackeichen** [comment]
Thanks for the clarification.  The "git tags" should be the root cause. 

So close the issue.
