### ISSUE TITLE
can't install...

### ISSUE THREAD

**Issue by Zibri** [python-scsi/python-scsi#134]
```
Processing d:\jms57x\python-scsi
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      WARNING setuptools_scm.run_cmd command git missing: [WinError 2] The system cannot find the file specified
      ERROR setuptools_scm._get_version_impl command git not found while parsing the scm, using fallbacks
      Traceback (most recent call last):
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools_scm\_get_version_impl.py", line 35, in parse_scm_version
          return _entrypoints.version_from_entrypoint(
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools_scm\_entrypoints.py", line 55, in version_from_entrypoint
          maybe_version: version.ScmVersion | None = fn(root, config=config)
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools_scm\git.py", line 208, in parse
          _require_command("git")
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools_scm\_run_cmd.py", line 207, in require_command
          raise CommandNotFoundError(name)
      setuptools_scm._run_cmd.CommandNotFoundError: git
      Traceback (most recent call last):
        File "C:\Users\Zibri\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Zibri\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Zibri\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools\dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools\dist.py", line 654, in finalize_options
          ep(self)
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 121, in infer_version
          _assign_version(dist, config)
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 56, in _assign_version
          _version_missing(config)
        File "C:\Users\Zibri\AppData\Local\Temp\pip-build-env-q43dngry\overlay\Lib\site-packages\setuptools_scm\_get_version_impl.py", line 112, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for D:\JMS57x\python-scsi.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by rosjat** [comment]
first of all this is not very helpful at all but first guess would be you seem to try to use this on a windows machine but this lib is trageted on linux. As far as I see at some point something want  to use git to get some tag info and this doesnt seem to be installed either.
