### ISSUE TITLE
example read_disc_information.py broken

### ISSUE THREAD

**Issue by folkertvanheusden** [python-scsi/python-scsi#137]
```
$ python3 read_disc_information.py iscsi://127.0.0.1/test/1
Traceback (most recent call last):
  File "/home/folkert/t/python-scsi/examples/read_disc_information.py", line 97, in <module>
    main()
  File "/home/folkert/t/python-scsi/examples/read_disc_information.py", line 55, in main
    cmd = s.readdiscinformation(data_type, alloc_len=512)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/folkert/.local/lib/python3.12/site-packages/pyscsi/pyscsi/scsi.py", line 435, in readdiscinformation
    opcode = self.device.opcodes.READ_DISC_INFORMATION
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Enum' has no attribute 'READ_DISC_INFORMATION'
```

**Comment by rosjat** [comment]
this is not really helpful, this example is intended for mmc (multimedia devices) so as long as you cant confirm which opcodes are assigned to self.device.opcodes I asume you simply got an enum that doesnt support the RED_DISC_INFORMATION opcode. So make sure your iscsi device a multimedia device

**Comment by folkertvanheusden** [comment]
thank you
